services:
  - type: web
    name: frontend
    env: static
    buildCommand: cd frontend && pnpm install && pnpm build
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
